### ISSUE TITLE
can we train sato with custom dataset?

### ISSUE THREAD

**Issue by swapnilwagh2204** [megagonlabs/sato#14]
can we train sato with out own data......i need it for the classification of semanic analysis. If yes...then how should i process with it?

**Comment by Siddhi1529** [comment]
@swapnilwagh2204  were u able to run the Sato model on your custom dataset? I need it for detecting semantic datatypes for datasets like Covid analysis

**Comment by swapnilwagh2204** [comment]
Unfortunately not.
